### ISSUE TITLE
Storage access permission on Android 14

### ISSUE THREAD

**Issue by david-lev** [HasanEltantawy/SQLiteViewer#2]
Hi, I saw your promising app on play store, I downloaded it but the app doesn't ask for access to storage permissions.

I'm using Galaxy S21, Android 14

Thanks!

![Screenshot_20240825_130011_Permission controller.jpg](https://github.com/user-attachments/assets/82f340d5-06f8-4021-b89f-2eed4255fe7b)

**Comment by 7Eltantawy** [comment]
This issue starting from android 12 and above due to new google policy we will fix this issue in next updates.

**Comment by 7Eltantawy** [comment]
This bug have been fixed.
